---
version: 1.5
released: 2017-07-14

# Database configurationw
database:
  username: tsb-heimdall
  password: h4Oo5cB5td9WwSF4
  host: 127.0.0.1
  port: 3306
  database: 'tsb-heimdall'
  prefix: 'tsb'
  local: 'D:\tools\Teamspeak-Server-3.5.0\teamspeak3-server_win64\ts3server.sqlitedb' #ToDo: Remove for deployment


# Teamspeak Server Query configuration
query:
  username: serveradmin
  password: 7K6h6KgS
  host: 127.0.0.1
  port: 10011
  floodRate: UNLIMITED
  debugLevel: OFF
  api-key: BABRZuJ7tz97W45G506Z2XnJQGk0uN_U9pZTKRS

# Selection for the server (if running multiple instances)
server:
  id: 1
  commandTimeout: 4000
  debugLevel: INFO

# General bot settings
bot:
  logToFile: true
  logToDb: true
  logFileZip: false
  nick: '[Bot] Heimdall'
  goOnlineMessage: "Hello all :)"     # Leave empty to deactivate message
  goOfflineMessage: "Going offline now!"    # Leave empty to deactivate message

# Commands that are disabled here are unavailable during runtime
# even if assigned to groups in the permissionsDefault.yml
commands:
  debug: true
  getPath: false
  hasPermission: true
  list:
    features: true
    users: true
  setLevel: true
  shutdown: false
  updateDescription: false
  doBackup: false
  stream:
    channels:
      - 3



# A list of administrators, who will be able to ignore any restriction (see: permissionsDefault.yml)
admins:
  - YourUUIDcomesHere
  - AnotherAdminUUID
  - 3t3UEmZyvl+JVNaR0lEZQlytvXs=

# Activate or deactivate some features
features:
  userHistory: true
  customWelcomeMessages: false
  webNotifications: false
  autoPromotion:
    active: true
    UpdateFrequency: 60000
  ChannelGroupSystem:
    lockedGroupId: 8  # Usually the guest group.
    unlockedGroupId: 10
    updateLimit: 60 # Minimum time before recalculate in Seconds
























