---
version: 1.5
released: 2017-07-14

# Database configuration
database:
  username: tsb-heimdall
  password: h4Oo5cB5td9WwSF4
  host: 127.0.0.1
  port: 3306
  database: 'teamspeak_heimdall'
  prefix: 'tsb'
  local: 'D:\tools\Teamspeak-Server-3.5.0\teamspeak3-server_win64\ts3server.sqlitedb' #ToDo: Remove for deployment


# Teamspeak Server Query configuration
query:
  username: serveradmin
  password: Y04l5RyR
  host: 127.0.0.1
  port: 10011
  floodRate: UNLIMITED
  debugLevel: OFF

# Selection for the server (if running multiple instances)
server:
  id: 1
  commandTimeout: 4000
  debugLevel: INFO

# General bot settings
bot:
  logToFile: true
  logToDb: true
  logFileZip: false
  nick: '[Bot] Heimdall'
  goOnlineMessage: ''     # Leave empty to deactivate message
  goOfflineMessage: ''    # Leave empty to deactivate message

# Commands that are disabled here are unavailable during runtime
# even if assigned to groups in the permission.yml
commands:
  debug: true
  getPath: false
  hasPermission: true
  list:
    features: true
    users: true
  setLevel: true
  shutdown: false
  updateDescription: false
  doBackup: false



# A list of administrators, who will be able to ignore any restriction (@see: permissions.yml)
admins:
  - YourUUIDcomesHere
  - AnotherAdminUUID

# Activate or deactivate some features
features:
  userHistory: true
  customWelcomeMessages: false
  webNotifications: false
  autoPromotion:
    active: true
    UpdateFrequency: 60000
























