# Set your user groups and permissions here.
# See reference.yml for a full list of permissions

guest:
  serverGroupId: 52
  rank: 0
  channel:
    - 44*
    - -44

public-gamer:
  serverGroupId: 53
  rank: 1
  channel:
    - 146*
    - -146
    - 176*
    - -176
  inherit: 'guest'


blutgarde:
  serverGroupId: 72
  rank: 2
  channel:
    - 137*
    - -137
    - -203
  inherit: 'public-gamer'


regular:
  rank: 2
  serverGroupId: 67
  inherit: 'public-gamer'


moderator:
  serverGroupId: 59
  rank: 3
  inherit: 'regular'
  permissions:
    - commands.help
    - commands.lock
  channel:
    - '*'

admin:
  serverGroupId: 63
  rank: 99
  channel:
    - '*'